### PR TITLE
Remove dependency on Events package

### LINKED ISSUE #756: [BUG] Events import failed after updating to v2.6
### What is the bug?
I have a project with a folder named `events` and after updating the opensearch-py from 2.5 to 2.6, where the `service time metrics` was added, I'm receiving the error below because python tries to import the `Events` from my project's home directory and not from the Events lib.
As `events` is a common name for folders and it might cause some trouble with other people too, do you have any suggestion for fixing this issue without renaming my project's folder to another name?

```text
 File "/home/[redacted]/venv/lib/python3.11/site-packages/opensearchpy/metrics/metrics_events.py", line 13, in <module>
    from events import Events
ImportError: cannot import name 'Events' from 'events'
```

### How can one reproduce the bug?
Add a folder `events` to your project and them call `from opensearchpy import OpenSearch`

### What is your host/environment?
python3.11 + ubuntu 20 + opensearch 2.6

### PR DESCRIPTION
**Pull request by noelleleigh**
### Description

Remove dependency on [Events](https://pypi.org/project/Events/) package to eliminate frequent module name collisions when `opensearch-py` is integrated into existing codebases which already have a module named `events`.

The usage of Events from #716 amounted to calling two functions in `opensearchpy.metrics.metrics_events.MetricsEvents`, so removing the indirection from Events was simple. This change has no effect on the public or private API of `opensearchpy.metrics.metrics_events.MetricsEvents`.

### Issues Resolved

Fixes #756

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by noelleleigh** [comment]
> ⚠️ Report is 139 commits behind head on main.

I think the coverage regression is a false positive due to this issue.

**Review by harshavamsi — APPROVED** [review]
Thanks!
