### PR TITLE
Fix Async request signer (issue #924)

### LINKED ISSUE #924: [BUG] Async request signer doesn't work anymore
### What is the bug?

Since version 3.0.0 the AWSV4SignerAsyncAuth throws the following error :
> AttributeError: 'bytes' object has no attribute 'items'

### How can one reproduce the bug?

Minimal reproduction code.

```python
import asyncio
import boto3
from opensearchpy import AsyncHttpConnection, AsyncOpenSearch, AWSV4SignerAsyncAuth


async def async_main() -> None:
    credentials = boto3.Session().get_credentials()
    auth = AWSV4SignerAsyncAuth(credentials, "us-east-1")
    client = AsyncOpenSearch(
        "http://localhost:9200",
        http_auth=auth,
        connection_class=AsyncHttpConnection,
    )

    await client.search(index="some-index", body={"query": "not_important"})


if __name__ == "__main__":
    asyncio.run(async_main())
```

The hostname doesn't need to exist. But you require a valid boto3 session.

### What is the expected behavior?

Not throwing exception.

### What is your host/environment?
Python 3.13 with opensearch-py[async] == 3.0.0

### Do you have any additional context?

I believe this regression has been introduced by #866 @brunomurino

### PR DESCRIPTION
**Pull request by snstanton**
### Description
Fixes the mismatch between the call args of _http_auth() in AsyncHttpConnection and the implementations.

### Issues Resolved
Closes #924

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: CHANGELOG.md [hunk 1]
```diff
@@ -12,6 +12,8 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 ### Deprecated
 ### Removed
 ### Fixed
+- Fix Async request signer doesn't work anymore ([932](https://github.com/opensearch-project/opensearch-py/pull/932))
```
Comment (dblock) [inline CHANGELOG.md:15]:
```suggestion
- Fix Async request signer ([932](https://github.com/opensearch-project/opensearch-py/pull/932))
```

**Review by dblock — APPROVED** [review]
LGTM, let's remove the "doesn't work anymore" it's not helpful

File: opensearchpy/connection/http_async.py [hunk 2]
```diff
@@ -203,10 +203,9 @@ async def perform_request(
             self._http_auth if isinstance(self._http_auth, aiohttp.BasicAuth) else None
         )
         if callable(self._http_auth):
-            req_headers = {
-                **req_headers,
-                **self._http_auth(method, url, query_string, body),
-            }
+            req_headers = self._http_auth(
+                method=method, url=url, body=body, headers=req_headers
+            )
```
[the remark this answers is not in the document]
Comment (snstanton) [reply opensearchpy/connection/http_async.py]: So I tried making this change as suggested, but it causes a test failure in `test_callable_in_request_session` because it is preserving the original headers.  Is the test incorrect, or is the suggested change incorrect?  In other words, is the expected behavior that the http_auth callback returns the updated header block, because that is waht the test implies.  In which case the original code above is correct.

[the remark this answers is not in the document]
Comment (abrahammurciano) [reply opensearchpy/connection/http_async.py]: LGTM

**Review by florianvazelle — APPROVED** [review]
