### ISSUE TITLE
[BUG] Events import failed after updating to v2.6

### ISSUE THREAD

**Issue by julianogv** [opensearch-project/opensearch-py#756]
### What is the bug?
I have a project with a folder named `events` and after updating the opensearch-py from 2.5 to 2.6, where the `service time metrics` was added, I'm receiving the error below because python tries to import the `Events` from my project's home directory and not from the Events lib.
As `events` is a common name for folders and it might cause some trouble with other people too, do you have any suggestion for fixing this issue without renaming my project's folder to another name?

```text
 File "/home/[redacted]/venv/lib/python3.11/site-packages/opensearchpy/metrics/metrics_events.py", line 13, in <module>
    from events import Events
ImportError: cannot import name 'Events' from 'events'
```

### How can one reproduce the bug?
Add a folder `events` to your project and them call `from opensearchpy import OpenSearch`

### What is your host/environment?
python3.11 + ubuntu 20 + opensearch 2.6

**Comment by dblock** [comment]
Should it be importing from the lib? Is this something we can/need to change in the library? If you know how, please PR?

**Comment by fnitsche** [comment]
Yep, we are hitting this issue too. We have an events folder and get the same error when we try to update to 2.6

**Comment by saimedhi** [comment]
@fnitsche, @julianogv, would you be interested in contributing a fix for this issue? Thanks!

**Comment by noelleleigh** [comment]
This issue was introduced in #716 and was released in [v2.6.0](https://github.com/opensearch-project/opensearch-py/releases/tag/v2.6.0). #716 added the [Events](https://pypi.org/project/Events/) package as a dependency, whose name is the source of the frequent name collisions.

To fix this issue, the code in `opensearchpy/metrics/metrics_events.py` needs to reimplement the features from `events.Events` itself to remove the dependency. Or, `opensearchpy/metrics/metrics_events.py` could be removed entirely, since the `MetricsEvents` class it defines isn't used anywhere except tests.

**Comment by noelleleigh** [comment]
I've opened [a PR to solve this issue](https://github.com/opensearch-project/opensearch-py/pull/1060).
